spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3307/mishik
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true